library(faraway)
library(olsrr)
model=lm(lpsa~.,data=prostate)
ols_step_best_subset(model)
ols_step_forward_p(model, penter=0.50, details=T)
ols_step_backward_p(model, prem=0.10, details=T)
ols_step_both_p(model, pent=0.15, prem=0.15, details=T)
model_forward = lm(lpsa~lcavol+lweight+svi+lbph+age+pgg45+lcp, data=prostate)
model_backward = lm(lpsa~lcavol+lweight+svi, data=prostate)
model_both = lm(lpsa~lcavol+lweight+svi+lbph, data=prostate)
ols_press(model_forward)
ols_press(model_backward)
ols_press(model_both)